Feature catalogue
H3ARTgg/iOS-FakeNFT-StarterProject-Public pull request #2
Opened 2023-06-23 13:38 UTC by H3ARTgg

2023-06-24 20:11 UTC, JuliDeveloper commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/UIBlockingProgressHUD.swift
> +        return UIApplication.shared.windows.first
Тут горит ворнинг на счет главного потока

`UIApplication.windows must be used from main thread only`

2023-06-24 20:11 UTC, JuliDeveloper commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/UIBlockingProgressHUD.swift
> +        window?.isUserInteractionEnabled = true
Тут тоже горит ворнинг на счет главного потока

2023-06-24 20:11 UTC, JuliDeveloper commented
Код хорошо структурирован, приятно читать)

2023-06-25 09:04 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/UIBlockingProgressHUD.swift
> +        window?.isUserInteractionEnabled = true
тоже сначала так сделал, но тут проблема в том, что если нет интернета, тогда с экрана не получится уйти и считай приложение зависло

2023-06-30 09:17 UTC, Pussmal requested changes
Привет! Работа огонь, ты очень много всего сделал. То что используешь combine и snapkit, тут просто без слов) 
По критичным штукам:
Забыл self проставить, проект не запускается. В комментариях написал где. 
При запуске много варнингов с констрейнтами, я когда закомментировал код с футером каталога, они пропали, возможно проблема где-то там. 

ну и с 429 кодом беда, как вариант накинул тебе свой костыль. 

в комбайне не разбираюсь, в вьюмоделях красиво все) Я не все посмотрел, но что в глаза бросилось предложил. 

Надеюсь ребята еще дополнят.

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCellViewModel.swift
> +                orderIds.append(id)
Тут у нескольких свойств забыл self проставить, не собирается проект

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/Cell/CatalogueCell.swift
> +        return imageView
мне кажется тут не хватает contentMode = .scaleAspectFill

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/Cell/CatalogueCellViewModel.swift
> +import Combine
Вот тут у меня прям сомнения на счет Kingfisher и UIKit во ViewModel , мне кажется лучше сделать отдельную сущность где будет качаться image, и по-хорошему мы все можем использовать эту сущность

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +        return view
Мне все таки кажется добавить лейбл в ячейку как-то попроще и это решит проблему с варнингами констрейнтов

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +        collectionView.insertSubview(refreshControl, at: 0)
Это можно перенести в настройку где через lazy создаешь коллекцию
collectionView.refreshControl = refreshControl 

в целом предлагаю все настройки внутри  viewDidLoad вынести в отдельные функции

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +    private func setupAlert() {
Тут предлагаю сделать AlertModel, собрать его во ViewModel и открывать его через байдинг. Посмотри как Саша делал это в трекере, у него это хорошо реализовано

https://github.com/vlknv/Tracker/tree/Sprint_17

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +                    self?.setupErrorContent()
ты круто это сделал, но мне кажется я могу предложить реализацию чуть попроще. 
Когда что-то идет не так, а в нашем случае основная проблема это отсутствие сети или превышенный лимит запросов, то мне кажется лучше в центре коллекции показать лейбл с текстом проблемы (нет интернета или превышен лимит),  а обновление делать через рефреш. Когда делаешь рефрешь скрываешь этот лейбл, а дальше от результата показываются ячейки или лейбл с ошибкой (см. фигму "No Signal" )
Короче сделать более привычное поведение, когда чего-то нет, ты свайпаешь чтобы обновить, типа такого:

https://disk.yandex.ru/i/LAmxoGA93T7CAA

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +import Combine
За комбайн и снапкит респект и уважуха что у тебя есть силы еще и это учить сверх основных заданий, это круто!

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +            id = "Header"
ты же не используешь хэдер, это можно удалить

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +        9
предлагаю сделать приватную структуру с константами и там хранить эти значения, или глобальную создать

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +        textView.font = Consts.Fonts.regular13
предлагаю тут  и у aboutAuthorTextView поставить для backgroundColor = .clear, когда медленный интернет черная полоса на экране, я ниже видео отправил, там видно

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +    private lazy var aboutAuthorTextView: UITextView = {
на темной теме цвет не меняется

<img width="313" alt="Снимок экрана 2023-06-30 в 11 21 18" src="https://github.com/H3ARTgg/iOS-FakeNFT-StarterProject-Public/assets/97784424/a9e227c1-e93e-4169-aa84-2e9e4ac186b6">

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +    override func viewDidLoad() {
Могу предложить запустить ProgressHUD, когда плохой интернет выглядит так:


https://github.com/H3ARTgg/iOS-FakeNFT-StarterProject-Public/assets/97784424/b620a10b-f6fa-4b29-91ca-6ca722966e7b

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +    }
Предлагаю все это вынести в отдельную функцию

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCell.swift
> +    private lazy var ratingImageView: UIImageView = {
Тут предлагаю использовать Юлин рейтинг (находится в AppBasic), он мне показался не плохой

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/MainTabBarController.swift
> +        let catalogueNavCon = UINavigationController(rootViewController: catalogueVC)
Мне кажется это лучше вынести в отдельную функцию

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Models/Rating.swift
> +final class Rating {
Юля сделала это общим, тут уже смотри сам что использовать

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +        viewModel?.$nfts.bind(action: { [weak self] _ in
как ранее писал, мне кажется хорошо бы все в отдельные функции вынести

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +        }
а не плохо)

2023-06-30 09:17 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewModel.swift
> +    func requestCollection() {
не знаю поможет это с ошибкой 429 или нет, но я придумал такой костыль. 
У меня в модели есть свойство -  private var nftsId: [String]? 
и есть свойство

    private var nfts: [Nft] = [] {
        didSet {
            guard let nftsId
            else {
                showCollectionView?(true)
                return
            }
            if nfts.count == nftsId.count {
                updateViewData?(true)
                showCollectionView?(true)
            }
        }
    }

соответственно провайдер грузит по одной nft и дрьавляет в массив, соответственно когда я загрузил все NFT у меня будет одинаковые количество элементов в массивах и как только это происходит, я показываю коллекцию

public func fetchNft() {
        guard let nftsId else { return }
        guard !nftsId.isEmpty else {
            showPlugView?(Consts.LocalizedStrings.plugLabelText)
            return
        }
        hideCollectionView?(true)
        nftsId.forEach({ [weak self] id in
            nftsProvider.fetchNft(id: id) { result in
                switch result {
                case .success(let nft):
                    DispatchQueue.main.async {
                        self?.nfts.append(nft)
                    }
                case .failure(let failure):
                    print(failure.localizedDescription)
                }
            }
        })
    }

2023-06-30 09:17 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Models/LikesResult.swift
> +struct LikesResult: Codable {
Предлагаю тут и в других моделях использовать нейминг как в примере

LikesNetworkModel

2023-06-30 09:17 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +    }
Круто 👍

2023-06-30 09:17 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/CollectionDetailsViewController.swift
> +        imageView.layer.maskedCorners = [.layerMinXMaxYCorner, .layerMaxXMaxYCorner]
Круто 👍

2023-06-30 09:17 UTC, Pussmal commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCellViewModel.swift
> +        dispatchGroup.notify(queue: .global()) { [weak self] in
queue: .global() прям отлично вообще что используешь такое

2023-06-30 09:17 UTC, AlexeyMotorin commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCell.swift
> +        }
красивая реализация на симуляторе получается

2023-06-30 15:16 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCellViewModel.swift
> +                orderIds.append(id)
Это кстати интересно, у меня почему-то все собирается и запускается, но self добавил

2023-06-30 15:23 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/Cell/CatalogueCellViewModel.swift
> +import Combine
Но в таком случае наша ячейка будет общаться с моделью, в этом и проблема.
А если выносить во ViewModel, то придется добавлять UIKit, так как происходит передача UIImage/UIImageView. 
Либо же забить и использовать kingfisher в ячейке

2023-06-30 15:34 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +        return view
Наверное. С констрейнтами пофиксил, а вот с этим, я не знаю. После обновления Xcode тоже самое стало вылазить в Tracker проекте еще. Тут тоже самое. Что-то не так с методом collectionView(referenceSizeForFooterInSection), а точнее с FlowLayout

2023-06-30 18:19 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +                    self?.setupErrorContent()
Можно было бы, но подумал, что прикольней дать вариацию для пользователя в обновлении экрана. Можно по кнопке, можно рефрешом

2023-06-30 18:24 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +    private func setupAlert() {
Да, реализация прикольная! Но так как алерт у меня используется один, пока так оставлю чтоль. Да и дальше как-то хочу без них обойтись во время ошибок (через лейблы, кастом прогресс хад и кнопочки)

2023-06-30 18:29 UTC, H3ARTgg commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +            id = "Header"
Это да, но чет всегда такую реализацию делаю всегда, зачем-то будто с запасом на будущее для хедера.
Уберу

2023-07-01 11:24 UTC, Pussmal approved these changes

2023-07-06 06:34 UTC, Helvetii951 commented on FakeNFT/Presentation/CatalogueFlow/CatalogueModule/CatalogueViewController.swift
> +        CustomProgressHUD.show()
Лучше добавить свойство isLoading во вью модель  и принимать решения о показе CustomProgressHUD уже через этот биндинг.

2023-07-06 06:34 UTC, Helvetii951 commented on FakeNFT/Presentation/CatalogueFlow/CollectionDetailsModule/Cell/CollectionDetailsCellViewModel.swift
> +    @Observable private(set) var isFailed: Bool = false
👍

2023-07-18 15:43 UTC, merged